### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by simon0h** [simon0h/Bill-Splitter#1]
**Web app specific**
- [ ] Custom domain

**Features/Improvements**
- [ ] Progress bar on top
- [ ] Export as screenshot option
- [ ] Autocomplete for common food items

**Bug fixes/tweaks**
- [ ] Add wrappers to CSS code
